/**
 * ── Resolution data: the bridge between the roster and the router ──────────────────────
 *
 * Two vendored JSON files describe OmniRoute's free providers, and this module is the only
 * thing that reads them:
 *
 *   `omniroute-catalog.json`   the roster — who offers free access, how, and what their
 *                              terms say. Generated by `tools/sync-omniroute-catalog.mjs`.
 *   `omniroute-resolved.json`  the routing configuration — endpoint, wire format and auth
 *                              shape for each row, plus an activation decision and its
 *                              reason. Generated by `tools/resolve-omniroute-endpoints.mjs`.
 *
 * It is deliberately a **leaf module**: it imports nothing but Node's `fs`. That matters
 * because two very different consumers need this data and they sit on opposite sides of
 * the dependency graph:
 *
 *   - `sources.js` needs the routable providers, to offer them on the generic
 *     OpenAI-compatible path. `sources.js` is the bottom of the graph, so anything it
 *     imports must be a leaf.
 *   - `providers/omniroute.js` needs the full activation picture, including refusals, to
 *     build descriptors.
 *
 * Reading JSON here rather than in either consumer is what keeps `sources.js` from having
 * to import the registry — which would close a cycle, since the registry's catalog reads
 * `PROVIDER_QUOTAS` from `sources.js`.
 *
 * **Nothing here performs network I/O.** Resolution happens offline in `tools/`.
 */

import { readFileSync, existsSync } from 'node:fs'

const CATALOG_URL = new URL('./omniroute-catalog.json', import.meta.url)
const RESOLVED_URL = new URL('./omniroute-resolved.json', import.meta.url)

function readJson(url, fallback) {
  if (!existsSync(url)) return fallback
  try {
    return JSON.parse(readFileSync(url, 'utf8'))
  } catch {
    // A malformed vendored file must not stop hammer from booting: the providers hammer
    // ships with are still valid, and the import is additive by definition.
    return fallback
  }
}

/** @returns {{ source: object, providers: object[] }} */
export function loadRoster() {
  const raw = readJson(CATALOG_URL, {})
  return { source: raw._source || {}, providers: Array.isArray(raw.providers) ? raw.providers : [] }
}

/**
 * @returns {{ source: object, providers: Record<string, object> }}
 *   provider key -> `{ activation, chatUrl?, modelsUrl?, auth?, blockedReason?, reason? }`
 */
export function loadResolutions() {
  const raw = readJson(RESOLVED_URL, {})
  return {
    source: raw._source || {},
    summary: raw.summary || {},
    providers: raw.providers && typeof raw.providers === 'object' ? raw.providers : {},
  }
}

const ACTIVATION_RANK = { active: 0, staged: 1, refused: 2 }

/**
 * Every roster row joined to its resolution, sorted by activation so the routable set
 * reads first.
 *
 * @returns {Array<{ key: string, access: string, tos: string, note: string|null, resolution: object }>}
 */
export function joinRosterWithResolutions() {
  const { providers: roster } = loadRoster()
  const { providers: resolutions } = loadResolutions()
  return roster
    .map(row => ({
      key: row.key,
      label: row.label || null,
      access: row.access,
      tos: row.tos,
      note: row.note || null,
      steadyTokensPerMonth: Number.isFinite(row.steadyTokensPerMonth) ? row.steadyTokensPerMonth : null,
      signupCreditTokens: Number.isFinite(row.signupCreditTokens) ? row.signupCreditTokens : null,
      resolution: resolutions[row.key] || { activation: 'staged', reason: 'no resolution recorded; run tools/resolve-omniroute-endpoints.mjs' },
    }))
    .sort((a, b) => (ACTIVATION_RANK[a.resolution.activation] ?? 9) - (ACTIVATION_RANK[b.resolution.activation] ?? 9))
}

/**
 * The subset of providers that can be reached over the generic OpenAI-compatible path.
 *
 * @returns {Array<{ key: string, chatUrl: string, modelsUrl: string|null, auth: object, tos: string }>}
 */
export function activeResolutions() {
  return joinRosterWithResolutions()
    .filter(row => row.resolution.activation === 'active' && row.resolution.chatUrl)
    .map(row => ({
      key: row.key,
      label: row.label,
      chatUrl: row.resolution.chatUrl,
      modelsUrl: row.resolution.modelsUrl || null,
      auth: row.resolution.auth || { kind: 'bearer' },
      tos: row.tos,
      access: row.access,
    }))
}

/** Rows whose terms flag forbids this use, each with the recorded reason. */
export function refusedResolutions() {
  return joinRosterWithResolutions()
    .filter(row => row.resolution.activation === 'refused')
    .map(row => ({ key: row.key, reason: row.resolution.reason || row.resolution.blockedReason || 'terms flag "avoid"' }))
}

/** Rows that are resolvable in principle but need provider-specific work first. */
export function stagedResolutions() {
  return joinRosterWithResolutions()
    .filter(row => row.resolution.activation === 'staged')
    .map(row => ({ key: row.key, reason: row.resolution.reason || row.resolution.blockedReason || 'not resolvable over the generic path' }))
}

/**
 * `sources.js` entries for the routable imports.
 *
 * The shape matches what the router already expects of a provider in `sources` — a `url`
 * to POST chat completions to, and `discoverable` so its model list can be fetched. Two
 * things are deliberate:
 *
 *   - `models: []`. Model rows arrive from `/v1/models` rather than being invented here,
 *     so an imported provider contributes nothing to the routing table until it is
 *     actually reached.
 *   - `lazyDiscovery: true`. This is what keeps the import honest about cost: the startup
 *     discovery wave skips these providers, so importing 40 of them does not become 40
 *     probes on every boot. They are discovered when something asks for them.
 *
 * `sources.js` spreads this *before* its own literal, so hammer's hand-configured
 * providers win any key collision without this module needing to know their names.
 *
 * @returns {Record<string, object>}
 */
export function lazyProviderSourceEntries() {
  const entries = {}
  for (const provider of activeResolutions()) {
    entries[provider.key] = {
      name: provider.label || provider.key,
      url: provider.chatUrl,
      modelsUrl: provider.modelsUrl || null,
      discoverable: true,
      lazyDiscovery: true,
      models: [],
      origin: 'omniroute',
      tos: provider.tos,
      authKind: provider.auth.kind,
      authOptional: provider.auth.optional === true,
    }
  }
  return entries
}

/** A count-and-reason summary of the import, for the startup line and the dashboard. */
export function importSummary() {
  const rows = joinRosterWithResolutions()
  const count = activation => rows.filter(row => row.resolution.activation === activation).length
  return {
    roster: rows.length,
    active: count('active'),
    refused: count('refused'),
    staged: count('staged'),
    resolvedAt: loadResolutions().source.generatedAt || null,
  }
}
